print("Input your information below:" + "\n")
first=input("First name- ")
last=input("Last name- ")
eyes=input("Eye Color- ")
hair=input("Hair Color- ")
month=input("Birth Month- ")
email=input("Email Address- ")
phone=input("Phone Number- ")
job=input("Job Title- ")
id_card=input("ID Number- ")
training=input("Have you completed advanced training? (Answer yes/no) ")

print("\nThe ID Card is:")
print("-------------------")
print(last.upper() + ", " + first.capitalize())
print(job.title())
print(f"ID: {id_card}\n")
print(email.lower())
print(phone + "\n")
#print("Hair: " + hair + "Eyes: " + eyes)
#print("Month: " + month + "Training: " + training)

print(f"Hair: {hair.capitalize():15} Eyes: {eyes.capitalize()}")
print(f"Month: {month.capitalize():14} Training: {training.capitalize()}")
print("------------------")

